---
title: "Resume"
author: "Jessie Gao"
output: html_document
---

### EDUCATION<br>
__Columbia University - Mailman School of Public Health, New York, NY, expected May 2023__<br>
• Master of Science (MS) in Biostatistics 

__Nankai University School of Finance, Tianjin, China, June 2020__<br>
• Bachelor of Economics in Insurance



### INTERNSHIP EXPERIENCE<br>
**The Illuminera Group, Shanghai, July 2020 - September 2020**                                 
_Project Assistant Intern - Three Innovation Department_ <br>
• Identified appealing selling points and communication angles through matrix analysis and text mining in 3 new product co- creation projects, created compelling data visualization including graphs, tables, charts, etc.<br>
•Established/maintained customer targeting models on TMIC with which the data accuracy improved 15%, extracted consumer data by SQL and made 200+ cold calls to further collect and screen consumer data<br>
• Conducted desk research to provide market/industry understanding regarding anti-aging skincare and eye makeup products<br>
• Designed 4 questionnaires for Kiehl’s and provided statistical analysis by Excel to identify winning concept for product launch

**Amazon, Beijing, June 2019 - December 2019** <br>
_Data Analysis Intern - Device & Digital Voice of Customer Department_<br>
• Completed benchmark research for 3 competitors independently to analyze 300,000+ customer feedback data of Amazon’s and its competitor across different social and internal platforms, built text-mining model, completed 400+ pieces of queries with more than 90% accuracy <br>
• Wrote 5 monthly reports of Kindle Content Product Experience to summarize customer experience related to Kindle usage in China and provided key insights for customer friction for business team to improve customer experience <br>
• Created 2 web crawler by Python to collect customer review data outside of Amazon.cn as to write the daily PRL of Kindle Oasis and Kindle Paperwhite and reflected product strengths and opportunities in China <br>
• Generated 2 SOPs for text-mining tools: Sprinklr and Heartbeat Textminer and provided training for the global VoC team <br>

### EXREACURRICULAR EXPERIENCE
**North China University Alliance Women Leadership Initiative, China, September 2019 - May 2020** <br>
_Sponsor_<br>
• Organized 5 forums around the self-identification and feminism, invited female elite to impart career experience, held “Women Week” to build networking for university female students

### SKILLS & QUALIFICATION
•Languages: Bilingual in Mandarin and English <br>
•Programming: SQL (expert); Python (Advanced); SAS (Advanced); R (Advanced); C++ (Beginner) Machine <br>
•Learning: kNN, Regression Model, SVC, Decision Tree, Random Forest Model, Cross-Validation <br>







